[package]
name = "robbot"
version = "0.1.0"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies.regex]
version = "1.0"

[dependencies.lazy_static]
version = "1.4"

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest"
features = ["json"]

[dependencies.dcc-scryfall]
path = "../dcc-scryfall/"

[dependencies.serenity]
features = ["framework", "standard_framework"]
git = "https://github.com/dcchut/serenity"
branch = "serenity-async-await"

[dependencies.tokio]
version = "0.2.0-alpha.6"

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.6"

[dependencies.dotenv]
version = "0.14"

[dependencies.chrono]
version = "0.4"

[dependencies.diesel]
version = "1.0"
features = ["sqlite", "chrono"]

[dependencies.chrono-humanize]
version = "0.0.11"