[package]
name = "robbot"
version = "0.1.1"
authors = ["Robert Usher <266585+dcchut@users.noreply.github.com>"]
edition = "2018"

[dependencies.libsqlite3-sys]
version = "0.16"
features = ["bundled"]

[dependencies.reqwest]
git = "https://github.com/seanmonstar/reqwest"
features = ["json"]

[dependencies.dcc-scryfall]
git = "https://github.com/dcchut/dcc-scryfall"

[dependencies.serenity]
features = ["framework", "standard_framework"]
git = "https://github.com/dcchut/serenity"
branch = "serenity-async-await"

[dependencies.tokio]
version = "0.2.0-alpha.6"

[dependencies.log]
version = "0.4"

[dependencies.env_logger]
version = "0.7"

[dependencies.dotenv]
version = "0.15"

[dependencies.chrono]
version = "0.4"

[dependencies.diesel]
version = "1.0"
features = ["sqlite", "chrono"]

[dependencies.chrono-humanize]
version = "0.0.11"