name: Check
on: [push]
jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]

    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Setup sqlite database for testing
        run: sqlite3 robbot.db < schema.sql
      - name: Tests
        run: cargo fmt -- --check && cargo check && cargo clippy -- -Dwarnings
        env:
          DATABASE_URL: sqlite:robbot.db

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        rust: [stable]
    
    steps:
      - uses: hecrj/setup-rust-action@v1
        with:
          rust-version: ${{ matrix.rust }}
      - uses: actions/checkout@master
      - name: Remove lockfile
        run: rm Cargo.lock
      - name: Setup sqlite database for compilation
        run: sqlite3 robbot.db < schema.sql
      - name: Build binary
        run: cargo build --release --bin robbot
        env:
          DATABASE_URL: sqlite:robbot.db
      - uses: actions/upload-artifact@master
        with:
          name: robbot
          path: target/release/robbot
